image: node:latest

stages:
  - build
  - test
  - deploy


before_script:
  - npm install

cache:
  paths:
    - node_modules/
    - dist/

generate:
  stage: build
  script:
    - npm run generate

test:
  stage: test
  script:
    - npm install -g jest
    - npm install -g vue-jest
    - npm test -- 'tests'

deploy_production:
  stage: deploy
  environment: Production
  only:
    refs:
      - master
  script:
    - cd functions && npm install && cd -
    - npm install -g firebase-tools
    - firebase use --token $FIREBASE_DEPLOY_KEY production
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
