image: node

stages:
  - build
  - test
  - deploy

before_script:
  - npm install

cache:
  paths:
    - node_modules/

job 1:
  stage: build
  script:
    - npm run generate

deploy_production:
  stage: deploy
  environment: Production
  only:
    refs:
      - master
      - develop
  script:
    - npm install -g firebase-tools
    - firebase use --token $FIREBASE_DEPLOY_KEY production
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
